// Auto-generated by generate_bindings.py - DO NOT EDIT
// Generated: deterministic (see git)

#pragma once

// One CopyComponent<T> per entity component (except ID/Tag, which
// the scene re-creates itself).
#define CANDY_COPY_COMPONENT_LIST(dst, src, enttMap) \
	CopyComponent<Candy::TransformComponent>(dst, src, enttMap); \
	CopyComponent<Candy::SpriteRendererComponent>(dst, src, enttMap); \
	CopyComponent<Candy::StaticMeshComponent>(dst, src, enttMap); \
	CopyComponent<Candy::SkeletalMeshComponent>(dst, src, enttMap); \
	CopyComponent<Candy::CircleRendererComponent>(dst, src, enttMap); \
	CopyComponent<Candy::CameraComponent>(dst, src, enttMap); \
	CopyComponent<Candy::LightComponent>(dst, src, enttMap); \
	CopyComponent<Candy::SkyboxComponent>(dst, src, enttMap); \
	CopyComponent<Candy::NativeScriptComponent>(dst, src, enttMap); \
	CopyComponent<Candy::Rigidbody2DComponent>(dst, src, enttMap); \
	CopyComponent<Candy::BoxCollider2DComponent>(dst, src, enttMap); \
	CopyComponent<Candy::CircleCollider2DComponent>(dst, src, enttMap); \
	CopyComponent<Candy::ScriptComponent>(dst, src, enttMap); \
	CopyComponent<Candy::AudioSourceComponent>(dst, src, enttMap); \
	CopyComponent<Candy::UITextBlockComponent>(dst, src, enttMap); \
	CopyComponent<Candy::UIButtonComponent>(dst, src, enttMap);

// One CopyComponentIfExists<T> per entity component.
#define CANDY_DUPLICATE_COMPONENT_LIST(dst, src) \
	CopyComponentIfExists<Candy::TransformComponent>(dst, src); \
	CopyComponentIfExists<Candy::SpriteRendererComponent>(dst, src); \
	CopyComponentIfExists<Candy::StaticMeshComponent>(dst, src); \
	CopyComponentIfExists<Candy::SkeletalMeshComponent>(dst, src); \
	CopyComponentIfExists<Candy::CircleRendererComponent>(dst, src); \
	CopyComponentIfExists<Candy::CameraComponent>(dst, src); \
	CopyComponentIfExists<Candy::LightComponent>(dst, src); \
	CopyComponentIfExists<Candy::SkyboxComponent>(dst, src); \
	CopyComponentIfExists<Candy::NativeScriptComponent>(dst, src); \
	CopyComponentIfExists<Candy::Rigidbody2DComponent>(dst, src); \
	CopyComponentIfExists<Candy::BoxCollider2DComponent>(dst, src); \
	CopyComponentIfExists<Candy::CircleCollider2DComponent>(dst, src); \
	CopyComponentIfExists<Candy::ScriptComponent>(dst, src); \
	CopyComponentIfExists<Candy::AudioSourceComponent>(dst, src); \
	CopyComponentIfExists<Candy::UITextBlockComponent>(dst, src); \
	CopyComponentIfExists<Candy::UIButtonComponent>(dst, src);
