// Auto-generated by generate_bindings.py - DO NOT EDIT
// Generated: 2026-08-19T20:45:58.735634

#pragma once

namespace YAML { class Emitter; class Node; }

namespace Candy {
namespace GeneratedSerialization {

// ---- TransformComponent ------------------------------------------------
inline void SerializeTransformComponent(YAML::Emitter& out, const Candy::TransformComponent& c)
{
	out << YAML::Key << "Translation" << YAML::Value << c.Translation;
	out << YAML::Key << "Rotation" << YAML::Value << c.Rotation;
	out << YAML::Key << "Scale" << YAML::Value << c.Scale;
}

inline void DeserializeTransformComponent(const YAML::Node& node, Candy::TransformComponent& c)
{
	if (auto n = node["Translation"])
		c.Translation = n.as<glm::vec3>();
	if (auto n = node["Rotation"])
		c.Rotation = n.as<glm::vec3>();
	if (auto n = node["Scale"])
		c.Scale = n.as<glm::vec3>();
}

// ---- SpriteRendererComponent ------------------------------------------------
inline void SerializeSpriteRendererComponent(YAML::Emitter& out, const Candy::SpriteRendererComponent& c)
{
	out << YAML::Key << "Color" << YAML::Value << c.Color;
	if (!c.TexturePath.empty())
		out << YAML::Key << "TexturePath" << YAML::Value << c.TexturePath;
	out << YAML::Key << "TilingFactor" << YAML::Value << c.TilingFactor;
}

inline void DeserializeSpriteRendererComponent(const YAML::Node& node, Candy::SpriteRendererComponent& c)
{
	if (auto n = node["Color"])
		c.Color = n.as<glm::vec4>();
	if (auto n = node["TexturePath"])
		c.TexturePath = n.as<std::string>();
	if (auto n = node["TilingFactor"])
		c.TilingFactor = n.as<float>();
}

// ---- StaticMeshComponent ------------------------------------------------
inline void SerializeStaticMeshComponent(YAML::Emitter& out, const Candy::StaticMeshComponent& c)
{
	if (!c.MeshPath.empty())
		out << YAML::Key << "MeshPath" << YAML::Value << c.MeshPath;
	if (!c.MaterialPaths.empty())
	{
		out << YAML::Key << "MaterialPaths" << YAML::Value;
		out << YAML::BeginSeq;
		for (const auto& v : c.MaterialPaths)
			out << YAML::Value << v;
		out << YAML::EndSeq;
	}
}

inline void DeserializeStaticMeshComponent(const YAML::Node& node, Candy::StaticMeshComponent& c)
{
	if (auto n = node["MeshPath"])
		c.MeshPath = n.as<std::string>();
	if (auto n = node["MaterialPaths"])
	{
		c.MaterialPaths.clear();
		for (const auto& v : n)
			c.MaterialPaths.push_back(v.as<std::string>());
	}
}

// ---- SkeletalMeshComponent ------------------------------------------------
inline void SerializeSkeletalMeshComponent(YAML::Emitter& out, const Candy::SkeletalMeshComponent& c)
{
	if (!c.MeshPath.empty())
		out << YAML::Key << "MeshPath" << YAML::Value << c.MeshPath;
	if (!c.MaterialPaths.empty())
	{
		out << YAML::Key << "MaterialPaths" << YAML::Value;
		out << YAML::BeginSeq;
		for (const auto& v : c.MaterialPaths)
			out << YAML::Value << v;
		out << YAML::EndSeq;
	}
	if (!c.ClipName.empty())
		out << YAML::Key << "ClipName" << YAML::Value << c.ClipName;
	out << YAML::Key << "Speed" << YAML::Value << c.Speed;
	out << YAML::Key << "Play" << YAML::Value << c.Play;
	out << YAML::Key << "Loop" << YAML::Value << c.Loop;
}

inline void DeserializeSkeletalMeshComponent(const YAML::Node& node, Candy::SkeletalMeshComponent& c)
{
	if (auto n = node["MeshPath"])
		c.MeshPath = n.as<std::string>();
	if (auto n = node["MaterialPaths"])
	{
		c.MaterialPaths.clear();
		for (const auto& v : n)
			c.MaterialPaths.push_back(v.as<std::string>());
	}
	if (auto n = node["ClipName"])
		c.ClipName = n.as<std::string>();
	if (auto n = node["Speed"])
		c.Speed = n.as<float>();
	if (auto n = node["Play"])
		c.Play = n.as<bool>();
	if (auto n = node["Loop"])
		c.Loop = n.as<bool>();
}

// ---- SkyboxComponent ------------------------------------------------
inline void SerializeSkyboxComponent(YAML::Emitter& out, const Candy::SkyboxComponent& c)
{
	if (!c.CubemapPath.empty())
		out << YAML::Key << "CubemapPath" << YAML::Value << c.CubemapPath;
	out << YAML::Key << "Intensity" << YAML::Value << c.Intensity;
	out << YAML::Key << "Exposure" << YAML::Value << c.Exposure;
}

inline void DeserializeSkyboxComponent(const YAML::Node& node, Candy::SkyboxComponent& c)
{
	if (auto n = node["CubemapPath"])
		c.CubemapPath = n.as<std::string>();
	if (auto n = node["Intensity"])
		c.Intensity = n.as<float>();
	if (auto n = node["Exposure"])
		c.Exposure = n.as<float>();
}

// ---- BoxCollider2DComponent ------------------------------------------------
inline void SerializeBoxCollider2DComponent(YAML::Emitter& out, const Candy::BoxCollider2DComponent& c)
{
	out << YAML::Key << "Offset" << YAML::Value << c.Offset;
	out << YAML::Key << "Size" << YAML::Value << c.Size;
	out << YAML::Key << "Density" << YAML::Value << c.Density;
	out << YAML::Key << "Friction" << YAML::Value << c.Friction;
	out << YAML::Key << "Restitution" << YAML::Value << c.Restitution;
	out << YAML::Key << "RestitutionThreshold" << YAML::Value << c.RestitutionThreshold;
}

inline void DeserializeBoxCollider2DComponent(const YAML::Node& node, Candy::BoxCollider2DComponent& c)
{
	if (auto n = node["Offset"])
		c.Offset = n.as<glm::vec2>();
	if (auto n = node["Size"])
		c.Size = n.as<glm::vec2>();
	if (auto n = node["Density"])
		c.Density = n.as<float>();
	if (auto n = node["Friction"])
		c.Friction = n.as<float>();
	if (auto n = node["Restitution"])
		c.Restitution = n.as<float>();
	if (auto n = node["RestitutionThreshold"])
		c.RestitutionThreshold = n.as<float>();
}

// ---- CircleCollider2DComponent ------------------------------------------------
inline void SerializeCircleCollider2DComponent(YAML::Emitter& out, const Candy::CircleCollider2DComponent& c)
{
	out << YAML::Key << "Offset" << YAML::Value << c.Offset;
	out << YAML::Key << "Radius" << YAML::Value << c.Radius;
	out << YAML::Key << "Density" << YAML::Value << c.Density;
	out << YAML::Key << "Friction" << YAML::Value << c.Friction;
	out << YAML::Key << "Restitution" << YAML::Value << c.Restitution;
	out << YAML::Key << "RestitutionThreshold" << YAML::Value << c.RestitutionThreshold;
}

inline void DeserializeCircleCollider2DComponent(const YAML::Node& node, Candy::CircleCollider2DComponent& c)
{
	if (auto n = node["Offset"])
		c.Offset = n.as<glm::vec2>();
	if (auto n = node["Radius"])
		c.Radius = n.as<float>();
	if (auto n = node["Density"])
		c.Density = n.as<float>();
	if (auto n = node["Friction"])
		c.Friction = n.as<float>();
	if (auto n = node["Restitution"])
		c.Restitution = n.as<float>();
	if (auto n = node["RestitutionThreshold"])
		c.RestitutionThreshold = n.as<float>();
}

// ---- ScriptComponent ------------------------------------------------
inline void SerializeScriptComponent(YAML::Emitter& out, const Candy::ScriptComponent& c)
{
	if (!c.ScriptPath.empty())
		out << YAML::Key << "ScriptPath" << YAML::Value << c.ScriptPath;
	if (!c.ClassName.empty())
		out << YAML::Key << "ClassName" << YAML::Value << c.ClassName;
}

inline void DeserializeScriptComponent(const YAML::Node& node, Candy::ScriptComponent& c)
{
	if (auto n = node["ScriptPath"])
		c.ScriptPath = n.as<std::string>();
	if (auto n = node["ClassName"])
		c.ClassName = n.as<std::string>();
}

// ---- AudioSourceComponent ------------------------------------------------
inline void SerializeAudioSourceComponent(YAML::Emitter& out, const Candy::AudioSourceComponent& c)
{
	if (!c.SoundPath.empty())
		out << YAML::Key << "SoundPath" << YAML::Value << c.SoundPath;
	out << YAML::Key << "Volume" << YAML::Value << c.Volume;
	out << YAML::Key << "Looping" << YAML::Value << c.Looping;
	out << YAML::Key << "PlayOnStart" << YAML::Value << c.PlayOnStart;
}

inline void DeserializeAudioSourceComponent(const YAML::Node& node, Candy::AudioSourceComponent& c)
{
	if (auto n = node["SoundPath"])
		c.SoundPath = n.as<std::string>();
	if (auto n = node["Volume"])
		c.Volume = n.as<float>();
	if (auto n = node["Looping"])
		c.Looping = n.as<bool>();
	if (auto n = node["PlayOnStart"])
		c.PlayOnStart = n.as<bool>();
}

} // namespace GeneratedSerialization
} // namespace Candy
