# Auto-generated by generate_bindings.py - DO NOT EDIT
# Generated: deterministic (see git)

from __future__ import annotations
from typing import Any, overload

class Vec2:
	x: float
	y: float
	@overload
	def __init__(self) -> None: ...
	@overload
	def __init__(self, float: float, float: float) -> None: ...

class Vec3:
	x: float
	y: float
	z: float
	@overload
	def __init__(self) -> None: ...
	@overload
	def __init__(self, float: float, float: float, float: float) -> None: ...

class Vec4:
	r: float
	g: float
	b: float
	a: float
	@overload
	def __init__(self) -> None: ...
	@overload
	def __init__(self, float: float, float: float, float: float, float: float) -> None: ...

class TagComponent:
	Tag: str
	def __init__(self) -> None: ...

class TransformComponent:
	Translation: Vec3
	Rotation: Vec3
	Scale: Vec3
	def __init__(self) -> None: ...

class SpriteRendererComponent:
	Color: Vec4
	TexturePath: str
	TilingFactor: float
	def __init__(self) -> None: ...

class StaticMeshComponent:
	MeshPath: str
	def __init__(self) -> None: ...

class SkeletalMeshComponent:
	MeshPath: str
	ClipName: str
	Speed: float
	Play: bool
	Loop: bool
	def __init__(self) -> None: ...

class CircleRendererComponent:
	Color: Vec4
	Thickness: float
	Fade: float
	def __init__(self) -> None: ...

class CameraComponent:
	def __init__(self) -> None: ...

class LightComponent:
	Type: LightType
	Color: Vec3
	Intensity: float
	Range: float
	InnerConeAngle: float
	OuterConeAngle: float
	CastShadows: bool
	def __init__(self) -> None: ...

class SkyboxComponent:
	CubemapPath: str
	Intensity: float
	Exposure: float
	def __init__(self) -> None: ...

class NativeScriptComponent:
	def __init__(self) -> None: ...

class BoxCollider2DComponent:
	Offset: Vec2
	Size: Vec2
	Density: float
	Friction: float
	Restitution: float
	RestitutionThreshold: float
	def __init__(self) -> None: ...

class CircleCollider2DComponent:
	Offset: Vec2
	Radius: float
	Density: float
	Friction: float
	Restitution: float
	RestitutionThreshold: float
	def __init__(self) -> None: ...

class ScriptComponent:
	ScriptPath: str
	ClassName: str
	def __init__(self) -> None: ...

class AudioSourceComponent:
	SoundPath: str
	Volume: float
	Looping: bool
	PlayOnStart: bool
	def __init__(self) -> None: ...

class TextBlockUIData:
	Text: str
	Color: Vec4
	Position: Vec2
	FontSize: float
	Visible: bool
	def __init__(self) -> None: ...

class ButtonUIData:
	Text: str
	FontSize: float
	Size: Vec2
	Position: Vec2
	OnClick: str
	Visible: bool
	def __init__(self) -> None: ...

class LightType:
	Directional: LightType  # type: ignore
	Point: LightType  # type: ignore
	Spot: LightType  # type: ignore

class BodyType:
	Static: BodyType  # type: ignore
	Dynamic: BodyType  # type: ignore
	Kinematic: BodyType  # type: ignore

# ============================================================================
# Manual stubs (hand-written bindings in PythonBindings.cpp)
# ============================================================================

class Rigidbody2DComponent:
	Type: BodyType
	FixedRotation: bool
	def __init__(self) -> None: ...
	def get_linear_velocity(self) -> Vec2: ...
	def set_linear_velocity(self, vx: float, vy: float) -> None: ...
	def apply_linear_impulse(self, ix: float, iy: float) -> None: ...

class UITextBlockComponent:
	def __init__(self) -> None: ...
	def set_text_visible(self, key: str, visible: bool) -> None: ...
	def set_text(self, key: str, text: str) -> None: ...

class UIButtonComponent:
	def __init__(self) -> None: ...
	def set_button_visible(self, key: str, visible: bool) -> None: ...
	def get_button_visible(self, key: str) -> bool: ...
	def set_button_text(self, key: str, text: str) -> None: ...
	def set_button_onclick(self, key: str, onclick: str) -> None: ...

class Entity:
	def get_component(self, type: str) -> Any: ...
	def has_component(self, type: str) -> bool: ...
	def add_component(self, type: str) -> None: ...
	def queue_free(self) -> None: ...
	def is_queued_for_deletion(self) -> bool: ...
	def call_function(self, func_name: str) -> None: ...
	@property
	def tag(self) -> str: ...
	@tag.setter
	def tag(self, value: str) -> None: ...
	@property
	def scene(self) -> Scene: ...

class ScriptObject:
	def __init__(self) -> None: ...
	def on_construct(self) -> None: ...
	def on_start(self) -> None: ...
	def on_tick(self, ts: float) -> None: ...
	def on_destroy(self) -> None: ...
	def on_collision_enter(self, other: Entity) -> None: ...
	def on_collision_exit(self, other: Entity) -> None: ...
	@property
	def _entity(self) -> Entity: ...

class Scene:
	def find_entity_by_tag(self, tag: str) -> Entity | None: ...
	def create_entity(self, name: str) -> Entity: ...
	def destroy_entity(self, entity: Entity) -> None: ...
	def queue_free(self, entity: Entity) -> None: ...
	def is_queued_for_deletion(self, entity: Entity) -> bool: ...
	def create_physics_body(self, entity: Entity) -> None: ...
	def recreate_physics_body(self, entity: Entity) -> None: ...
	def instantiate_script(self, entity: Entity) -> None: ...

# Module-level functions
def is_key_pressed(key: str) -> bool: ...
def play_one_shot(path: str, volume: float = 1.0) -> None: ...