#pragma once

//from glfw3.h
#define CANDY_MOUSE_BUTTON_1         0
#define CANDY_MOUSE_BUTTON_2         1
#define CANDY_MOUSE_BUTTON_3         2
#define CANDY_MOUSE_BUTTON_4         3
#define CANDY_MOUSE_BUTTON_5         4
#define CANDY_MOUSE_BUTTON_6         5
#define CANDY_MOUSE_BUTTON_7         6
#define CANDY_MOUSE_BUTTON_8         7
#define CANDY_MOUSE_BUTTON_LAST      CANDY_MOUSE_BUTTON_8
#define CANDY_MOUSE_BUTTON_LEFT      CANDY_MOUSE_BUTTON_1
#define CANDY_MOUSE_BUTTON_RIGHT     CANDY_MOUSE_BUTTON_2
#define CANDY_MOUSE_BUTTON_MIDDLE    CANDY_MOUSE_BUTTON_3