// Auto-generated by generate_bindings.py - DO NOT EDIT
// Generated: deterministic (see git)

#pragma once

namespace Candy {
namespace GeneratedUI {

// ---- TagComponent ------------------------------------------------
inline void DrawTagComponentFields(Candy::TagComponent& c)
{
	ImGuiUtils::DrawInputText("Tag", c.Tag);
}

// ---- TransformComponent ------------------------------------------------
inline void DrawTransformComponentFields(Candy::TransformComponent& c)
{
	ImGuiUtils::DrawVec3Control("Translation", c.Translation);
	ImGuiUtils::DrawVec3Control("Rotation", c.Rotation);
	ImGuiUtils::DrawVec3Control("Scale", c.Scale);
}

// ---- SpriteRendererComponent ------------------------------------------------
inline void DrawSpriteRendererComponentFields(Candy::SpriteRendererComponent& c)
{
	ImGuiUtils::DrawColorEdit4("Color", c.Color);
	ImGuiUtils::DrawInputText("TexturePath", c.TexturePath);
	ImGuiUtils::DrawDragFloat("TilingFactor", c.TilingFactor);
}

// ---- StaticMeshComponent ------------------------------------------------
inline void DrawStaticMeshComponentFields(Candy::StaticMeshComponent& c)
{
	ImGuiUtils::DrawInputText("MeshPath", c.MeshPath);
	ImGuiUtils::DrawMultilineStringList("MaterialPaths", c.MaterialPaths);
}

// ---- SkeletalMeshComponent ------------------------------------------------
inline void DrawSkeletalMeshComponentFields(Candy::SkeletalMeshComponent& c)
{
	ImGuiUtils::DrawInputText("MeshPath", c.MeshPath);
	ImGuiUtils::DrawMultilineStringList("MaterialPaths", c.MaterialPaths);
	ImGuiUtils::DrawInputText("ClipName", c.ClipName);
	ImGuiUtils::DrawDragFloat("Speed", c.Speed);
	ImGuiUtils::DrawCheckbox("Play", c.Play);
	ImGuiUtils::DrawCheckbox("Loop", c.Loop);
}

// ---- CircleRendererComponent ------------------------------------------------
inline void DrawCircleRendererComponentFields(Candy::CircleRendererComponent& c)
{
	ImGuiUtils::DrawColorEdit4("Color", c.Color);
	ImGuiUtils::DrawDragFloat("Thickness", c.Thickness);
	ImGuiUtils::DrawDragFloat("Fade", c.Fade);
}

// ---- LightComponent ------------------------------------------------
inline void DrawLightComponentFields(Candy::LightComponent& c)
{
	ImGuiUtils::DrawVec3Control("Color", c.Color);
	ImGuiUtils::DrawDragFloat("Intensity", c.Intensity);
	ImGuiUtils::DrawDragFloat("Range", c.Range);
	ImGuiUtils::DrawDragFloat("InnerConeAngle", c.InnerConeAngle);
	ImGuiUtils::DrawDragFloat("OuterConeAngle", c.OuterConeAngle);
	ImGuiUtils::DrawCheckbox("CastShadows", c.CastShadows);
}

// ---- SkyboxComponent ------------------------------------------------
inline void DrawSkyboxComponentFields(Candy::SkyboxComponent& c)
{
	ImGuiUtils::DrawInputText("CubemapPath", c.CubemapPath);
	ImGuiUtils::DrawDragFloat("Intensity", c.Intensity);
	ImGuiUtils::DrawDragFloat("Exposure", c.Exposure);
}

// ---- BoxCollider2DComponent ------------------------------------------------
inline void DrawBoxCollider2DComponentFields(Candy::BoxCollider2DComponent& c)
{
	ImGuiUtils::DrawDragFloat2("Offset", c.Offset);
	ImGuiUtils::DrawDragFloat2("Size", c.Size);
	ImGuiUtils::DrawDragFloat("Density", c.Density);
	ImGuiUtils::DrawDragFloat("Friction", c.Friction);
	ImGuiUtils::DrawDragFloat("Restitution", c.Restitution);
	ImGuiUtils::DrawDragFloat("RestitutionThreshold", c.RestitutionThreshold);
}

// ---- CircleCollider2DComponent ------------------------------------------------
inline void DrawCircleCollider2DComponentFields(Candy::CircleCollider2DComponent& c)
{
	ImGuiUtils::DrawDragFloat2("Offset", c.Offset);
	ImGuiUtils::DrawDragFloat("Radius", c.Radius);
	ImGuiUtils::DrawDragFloat("Density", c.Density);
	ImGuiUtils::DrawDragFloat("Friction", c.Friction);
	ImGuiUtils::DrawDragFloat("Restitution", c.Restitution);
	ImGuiUtils::DrawDragFloat("RestitutionThreshold", c.RestitutionThreshold);
}

// ---- ScriptComponent ------------------------------------------------
inline void DrawScriptComponentFields(Candy::ScriptComponent& c)
{
	ImGuiUtils::DrawInputText("ScriptPath", c.ScriptPath);
	ImGuiUtils::DrawInputText("ClassName", c.ClassName);
}

// ---- AudioSourceComponent ------------------------------------------------
inline void DrawAudioSourceComponentFields(Candy::AudioSourceComponent& c)
{
	ImGuiUtils::DrawInputText("SoundPath", c.SoundPath);
	ImGuiUtils::DrawDragFloat("Volume", c.Volume);
	ImGuiUtils::DrawCheckbox("Looping", c.Looping);
	ImGuiUtils::DrawCheckbox("PlayOnStart", c.PlayOnStart);
}

// ---- TextBlockUIData ------------------------------------------------
inline void DrawTextBlockUIDataFields(Candy::TextBlockUIData& c)
{
	ImGuiUtils::DrawInputText("Text", c.Text);
	ImGuiUtils::DrawColorEdit4("Color", c.Color);
	ImGuiUtils::DrawDragFloat2("Position", c.Position);
	ImGuiUtils::DrawDragFloat("FontSize", c.FontSize);
	ImGuiUtils::DrawCheckbox("Visible", c.Visible);
}

// ---- ButtonUIData ------------------------------------------------
inline void DrawButtonUIDataFields(Candy::ButtonUIData& c)
{
	ImGuiUtils::DrawInputText("Text", c.Text);
	ImGuiUtils::DrawDragFloat("FontSize", c.FontSize);
	ImGuiUtils::DrawDragFloat2("Size", c.Size);
	ImGuiUtils::DrawDragFloat2("Position", c.Position);
	ImGuiUtils::DrawInputText("OnClick", c.OnClick);
	ImGuiUtils::DrawCheckbox("Visible", c.Visible);
}

} // namespace GeneratedUI
} // namespace Candy
