// Auto-generated by generate_bindings.py - DO NOT EDIT
// Generated: 2026-07-29T00:54:34.132414

// ============================================================================
// Base Types (glm)
// ============================================================================

// Vec2
py::class_<glm::vec2>(m, "Vec2")
    .def(py::init<>())
    .def(py::init<float, float>())
    .def_readwrite("x", &glm::vec2::x)
    .def_readwrite("y", &glm::vec2::y)
        .def("__repr__", [](const glm::vec2& v) {
            return "Vec2(" + std::to_string(v.x) + ", " + std::to_string(v.y) + ")";
        })
    ;

// Vec3
py::class_<glm::vec3>(m, "Vec3")
    .def(py::init<>())
    .def(py::init<float, float, float>())
    .def_readwrite("x", &glm::vec3::x)
    .def_readwrite("y", &glm::vec3::y)
    .def_readwrite("z", &glm::vec3::z)
        .def("__repr__", [](const glm::vec3& v) {
            return "Vec3(" + std::to_string(v.x) + ", " + std::to_string(v.y) + ", " + std::to_string(v.z) + ")";
        })
    ;

// Vec4
py::class_<glm::vec4>(m, "Vec4")
    .def(py::init<>())
    .def(py::init<float, float, float, float>())
    .def_readwrite("r", &glm::vec4::r)
    .def_readwrite("g", &glm::vec4::g)
    .def_readwrite("b", &glm::vec4::b)
    .def_readwrite("a", &glm::vec4::a)
        .def("__repr__", [](const glm::vec4& v) {
            return "Vec4(" + std::to_string(v.r) + ", " + std::to_string(v.g) + ", " + std::to_string(v.b) + ", " + std::to_string(v.a) + ")";
        })
    ;

// ============================================================================
// Component Structs
// ============================================================================

// TagComponent
py::class_<Candy::TagComponent>(m, "TagComponent")
    .def(py::init<>())
    .def_readwrite("Tag", &Candy::TagComponent::Tag)
    ;

// TransformComponent
py::class_<Candy::TransformComponent>(m, "TransformComponent")
    .def(py::init<>())
    .def_readwrite("Translation", &Candy::TransformComponent::Translation)
    .def_readwrite("Rotation", &Candy::TransformComponent::Rotation)
    .def_readwrite("Scale", &Candy::TransformComponent::Scale)
    ;

// SpriteRendererComponent
py::class_<Candy::SpriteRendererComponent>(m, "SpriteRendererComponent")
    .def(py::init<>())
    .def_readwrite("Color", &Candy::SpriteRendererComponent::Color)
    .def_readwrite("TexturePath", &Candy::SpriteRendererComponent::TexturePath)
    .def_readwrite("TilingFactor", &Candy::SpriteRendererComponent::TilingFactor)
    ;

// BoxCollider2DComponent
py::class_<Candy::BoxCollider2DComponent>(m, "BoxCollider2DComponent")
    .def(py::init<>())
    .def_readwrite("Offset", &Candy::BoxCollider2DComponent::Offset)
    .def_readwrite("Size", &Candy::BoxCollider2DComponent::Size)
    .def_readwrite("Density", &Candy::BoxCollider2DComponent::Density)
    .def_readwrite("Friction", &Candy::BoxCollider2DComponent::Friction)
    .def_readwrite("Restitution", &Candy::BoxCollider2DComponent::Restitution)
    ;

// CircleCollider2DComponent
py::class_<Candy::CircleCollider2DComponent>(m, "CircleCollider2DComponent")
    .def(py::init<>())
    .def_readwrite("Offset", &Candy::CircleCollider2DComponent::Offset)
    .def_readwrite("Radius", &Candy::CircleCollider2DComponent::Radius)
    .def_readwrite("Density", &Candy::CircleCollider2DComponent::Density)
    .def_readwrite("Friction", &Candy::CircleCollider2DComponent::Friction)
    .def_readwrite("Restitution", &Candy::CircleCollider2DComponent::Restitution)
    ;

// ScriptComponent
py::class_<Candy::ScriptComponent>(m, "ScriptComponent")
    .def(py::init<>())
    .def_readwrite("ScriptPath", &Candy::ScriptComponent::ScriptPath)
    .def_readwrite("ClassName", &Candy::ScriptComponent::ClassName)
    ;

// AudioSourceComponent
py::class_<Candy::AudioSourceComponent>(m, "AudioSourceComponent")
    .def(py::init<>())
    .def_readwrite("SoundPath", &Candy::AudioSourceComponent::SoundPath)
    .def_readwrite("Volume", &Candy::AudioSourceComponent::Volume)
    .def_readwrite("Looping", &Candy::AudioSourceComponent::Looping)
    .def_readwrite("PlayOnStart", &Candy::AudioSourceComponent::PlayOnStart)
    ;

// TextBlockUIData
py::class_<Candy::TextBlockUIData>(m, "TextBlockUIData")
    .def(py::init<>())
    .def_readwrite("Text", &Candy::TextBlockUIData::Text)
    .def_readwrite("Color", &Candy::TextBlockUIData::Color)
    .def_readwrite("Position", &Candy::TextBlockUIData::Position)
    .def_readwrite("FontSize", &Candy::TextBlockUIData::FontSize)
    .def_readwrite("Visible", &Candy::TextBlockUIData::Visible)
    ;

// ButtonUIData
py::class_<Candy::ButtonUIData>(m, "ButtonUIData")
    .def(py::init<>())
    .def_readwrite("Text", &Candy::ButtonUIData::Text)
    .def_readwrite("FontSize", &Candy::ButtonUIData::FontSize)
    .def_readwrite("Size", &Candy::ButtonUIData::Size)
    .def_readwrite("Position", &Candy::ButtonUIData::Position)
    .def_readwrite("OnClick", &Candy::ButtonUIData::OnClick)
    .def_readwrite("Visible", &Candy::ButtonUIData::Visible)
    ;

// ============================================================================
// Enums
// ============================================================================

// BodyType
py::enum_<Candy::Rigidbody2DComponent::BodyType>(m, "BodyType")
    .value("Static", Candy::Rigidbody2DComponent::BodyType::Static)
    .value("Dynamic", Candy::Rigidbody2DComponent::BodyType::Dynamic)
    .value("Kinematic", Candy::Rigidbody2DComponent::BodyType::Kinematic)
    ;
